name: Deploy to Raspberry Pi
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code into existing repository
        # Use the full, absolute path to your directory
        working-directory: /home/mateusz/airflow 
        run: |
          echo "Updating repository in existing folder..."
          git pull origin main
          echo "Update complete."

      - name: Update dependencies
        # Use the same absolute path here
        working-directory: /home/mateusz/airflow
        run: |
          uv sync

      - run: echo "Code and dependencies are now set up on your Pi!"
